# Generated by Django 5.0.6 on 2024-07-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='subject',
        ),
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.CharField(default='Notes for second semestes of rgpv diploma', max_length=300),
            preserve_default=False,
        ),
    ]
