# Generated by Django 5.0.6 on 2024-07-11 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.ForeignKey(default=' ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.subject'),
        ),
    ]
