# Generated by Django 5.0.6 on 2024-07-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_note_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='total_downlods',
            field=models.IntegerField(default=0),
        ),
    ]
