# Generated by Django 5.0.6 on 2024-07-16 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_note_total_downlods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='total_downlods',
            new_name='total_downloads',
        ),
    ]
